name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Install Cordova using NPM
      run: npm install -g cordova
    - name: Cordova add Platform Android
      run: cordova platform add android
    - name: Cordova, Build!
      run: cordova build android

    - uses: actions/upload-artifact@v4
      name: Upload Artifact
      with:
        name: app.apk
        path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
        overwrite: true
