name: Cordova Build Apps
run-name: build cordova apps
on: [push]
jobs:
  Build-Unsigned-iOS-App:
    runs-on: macos-latest
    steps:
      - name: Install Cordova
        run: npm install -g cordova
      - name: Add Cordova Platform iOS
        run: cordova platform add ios
      - name: Build ipa
        run: cordova build ios
  Build-Android-App:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cordova
        run: npm install -g cordova
      - name: Install Android Tools
        run: echo "Add Lines here to Install Gradle and Android Build Tools"
      - name: Add Cordova Platform Android
        run: cordova platform add android
      - name: Build ipa
        run: cordova build android
